# Generated by Django 4.1.7 on 2023-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=250)),
                ('mainimg', models.ImageField(blank=True, upload_to='Projects')),
                ('respornsive', models.ImageField(blank=True, upload_to='Projects')),
                ('logo', models.ImageField(blank=True, upload_to='Projects')),
                ('discription1', models.TextField(max_length=70)),
                ('discription2', models.TextField(max_length=70)),
                ('link', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='ServicesLogo')),
            ],
        ),
    ]
