# Generated by Django 4.1.7 on 2023-02-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام دسته بندی')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='آیا نمایش داده شود؟')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک صفحه')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mysite.mainmenu', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['position'],
            },
        ),
    ]
