# Generated by Django 4.1.7 on 2023-04-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_mainmenu"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipsAbout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="نکته :"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "نکاتی درباره ی سایت",
                "verbose_name_plural": "نکاتی درباره ی سایت",
                "ordering": ["-created"],
            },
        ),
    ]
