# Generated by Django 4.1.7 on 2023-04-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0006_alter_contentbox_options_alter_mainmenu_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="icon",
            field=models.ImageField(upload_to="ServicesLogo"),
        ),
    ]
