# Generated by Django 4.2.3 on 2023-08-12 22:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0009_attribute_footer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="سوال"
                    ),
                ),
                (
                    "answer",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="جواب"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": " سوال متداول",
                "verbose_name_plural": "سوالات متداول",
                "ordering": ["-created"],
            },
        ),
    ]
