# Generated by Django 4.2.3 on 2023-08-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0010_questions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Questions",
            new_name="Question",
        ),
        migrations.AddField(
            model_name="footer",
            name="instagram",
            field=models.TextField(null=True, verbose_name="ادرس اینستاگرام"),
        ),
        migrations.AddField(
            model_name="footer",
            name="linkdin",
            field=models.TextField(null=True, verbose_name="ادرس لینک دین"),
        ),
        migrations.AddField(
            model_name="footer",
            name="telegram",
            field=models.TextField(null=True, verbose_name="ادرس تلگرام"),
        ),
        migrations.AddField(
            model_name="footer",
            name="twwiter",
            field=models.TextField(null=True, verbose_name="ادرس توییتر"),
        ),
        migrations.AddField(
            model_name="footer",
            name="whatsapp",
            field=models.TextField(null=True, verbose_name="ادرس واتساپ"),
        ),
        migrations.AddField(
            model_name="footer",
            name="youtube",
            field=models.TextField(null=True, verbose_name="ادرس یوتیوب"),
        ),
    ]
