# Generated by Django 4.2.3 on 2023-08-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0011_rename_questions_question_footer_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="address",
            field=models.TextField(null=True, verbose_name="لینک"),
        ),
    ]
