# Generated by Django 4.1.7 on 2023-04-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "verbose_name": "تیکت های سایت",
                "verbose_name_plural": "تیکت های سایت",
            },
        ),
    ]
