# Generated by Django 4.2.3 on 2023-08-12 14:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="message",
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=3000),
        ),
    ]
