# Generated by Django 4.1.7 on 2023-04-16 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_ipaddress_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("users", models.CharField(max_length=500, verbose_name="کاربر")),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نظرات"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "articles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.article",
                        verbose_name="پست",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.comment",
                        verbose_name="پست جواب داده شده",
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت",
                "verbose_name_plural": "کامنت ها",
                "ordering": ("-created",),
            },
        ),
    ]
