# Generated by Django 4.1.7 on 2023-04-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="parent",
            new_name="parent_id",
        ),
    ]
