# Generated by Django 4.2.3 on 2023-08-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_article_options_favorite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="user",
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorites",
                to="blog.ipaddress",
                verbose_name=" کاربر",
            ),
        ),
    ]
