# Generated by Django 4.2.3 on 2023-08-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_favorite_user_favorite_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="user",
            new_name="user_ip_address",
        ),
    ]
