# Generated by Django 4.2.3 on 2023-08-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_rename_user_favorite_user_ip_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="user_ip_address",
        ),
        migrations.AddField(
            model_name="favorite",
            name="user_ip_address",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="blog.ipaddress",
                verbose_name=" کاربر",
            ),
            preserve_default=False,
        ),
    ]
