# Generated by Django 4.2.3 on 2023-08-12 14:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_remove_favorite_user_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="متن مقاله"
            ),
        ),
    ]
